// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAklAfJLvyKX0rAWLVgKaBe0r__6g1Mv98',
    appId: '1:730885610221:web:1695a60ca00df282e88ae4',
    messagingSenderId: '730885610221',
    projectId: 'fir-crud-f3fb9',
    authDomain: 'fir-crud-f3fb9.firebaseapp.com',
    storageBucket: 'fir-crud-f3fb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7io-Q-EiP1fxs3AjlPN7sjAWDwNq7pI4',
    appId: '1:730885610221:android:a7c65dbb70c3bd73e88ae4',
    messagingSenderId: '730885610221',
    projectId: 'fir-crud-f3fb9',
    storageBucket: 'fir-crud-f3fb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_sCG6phFgxdyaNYBFuyrz--GDWpWucIA',
    appId: '1:730885610221:ios:0b5f7b80e2de913fe88ae4',
    messagingSenderId: '730885610221',
    projectId: 'fir-crud-f3fb9',
    storageBucket: 'fir-crud-f3fb9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCurd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_sCG6phFgxdyaNYBFuyrz--GDWpWucIA',
    appId: '1:730885610221:ios:0b5f7b80e2de913fe88ae4',
    messagingSenderId: '730885610221',
    projectId: 'fir-crud-f3fb9',
    storageBucket: 'fir-crud-f3fb9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCurd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAklAfJLvyKX0rAWLVgKaBe0r__6g1Mv98',
    appId: '1:730885610221:web:b21ffe80643c723ae88ae4',
    messagingSenderId: '730885610221',
    projectId: 'fir-crud-f3fb9',
    authDomain: 'fir-crud-f3fb9.firebaseapp.com',
    storageBucket: 'fir-crud-f3fb9.firebasestorage.app',
  );
}
